name: Build Resume

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.10.0

      - name: Run build
        run: devbox run build

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            resume.md
            out/resume.pdf
            out/resume.html
            resume.css
          generate_release_notes: true